In [1]:
from pathlib import Path
import pandas as pd
import yaml

from data_prep.config import load_config

project_root = Path.cwd().resolve()
if project_root.name == "notebooks":
    project_root = project_root.parent

config_path = project_root / "configs" / "healthcare-prep.yaml"
config = load_config(config_path)

raw_data_dir = Path(config.get("staging_dir", "./data/raw/healthcare-analytics-patient-flow-data")).expanduser()
if not raw_data_dir.is_absolute():
    raw_data_dir = project_root / raw_data_dir

raw_csv = raw_data_dir / "healthcare_analytics_patient_flow_data.csv"
if not raw_csv.exists():
    raw_csv = project_root / "data" / "raw" / "healthcare-analytics-patient-flow-data" / "healthcare_analytics_patient_flow_data.csv"

if not raw_csv.exists():
    raise FileNotFoundError(f"Raw dataset not found at: {raw_csv}")

df = pd.read_csv(raw_csv)
df.head()

,Patient Id,Patient Admission Date,Patient Admission Time,Merged,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime
0,780-96-6113,9/9/2024,9:25:00 AM,W. Breede,Female,63,African American,NaN,Not Admission,5.0,32
1,714-35-6722,9/9/2024,4:42:00 PM,Y. Baldetti,Male,31,Asian,Orthopedics,Not Admission,NaN,22
2,571-85-3714,9/9/2024,12:14:00 AM,M. Semerad,Male,75,White,General Practice,Not Admission,NaN,16
3,404-43-9499,9/9/2024,8:33:00 PM,K. Blaydes,Male,79,African American,General Practice,Admission,NaN,38
4,552-51-5855,9/9/2024,7:25:00 PM,F. Dickerson,Female,24,African American,NaN,Admission,NaN,36

In [2]:
from data_prep.timeseries import summarize_integer_alignment

# Prepare the timestamped admissions series and run the two-stage binning workflow.
prepared_df = df[["Patient Id", "Patient Admission Date", "Patient Admission Time"]].copy()
prepared_df["timestamp"] = pd.to_datetime(
    prepared_df["Patient Admission Date"].astype(str).str.strip()
    + " "
    + prepared_df["Patient Admission Time"].astype(str).str.strip(),
    format="%d/%m/%Y %I:%M:%S %p",
    errors="coerce",
)

prepared_df = prepared_df.dropna(subset=["timestamp"]).copy()
summary = summarize_integer_alignment(prepared_df[["timestamp"]], timestamp_col="timestamp")

phase1_raw_series = summary["original_series"]
phase2_aligned_series = summary["aligned_series"]

output_dir = Path(config["prepared_dataset_dir"]).expanduser()
output_dir.mkdir(parents=True, exist_ok=True)
arrival_path = output_dir / "arrival_intensity.csv"
phase2_aligned_series.to_csv(arrival_path, index=False)

config["arrival_intensity_path"] = str(arrival_path)
config["arrival_intensity_window"] = summary["algorithm_window"]
config["arrival_intensity_alignment_status"] = summary["status"]
config["arrival_intensity_alignment_message"] = summary["message"]
with config_path.open("w", encoding="utf-8") as f:
    yaml.safe_dump(config, f, sort_keys=False)

print("Selected window:", summary["algorithm_window"])
print("Window unit:", summary["window_unit"])
print("Intensity unit:", summary["intensity_unit"])
print("Alignment status:", summary["status"])
print(summary["message"])
print("\nPhase 1: raw count-binning output from the original algorithm")
if phase1_raw_series.empty:
    print("No raw algorithm bins were produced.")
else:
    display(phase1_raw_series[["bin_id", "bin_start", "bin_end", "window", "count", "intensity"]].head())

print("\nPhase 2: integer-aligned output from the bin-alignment phase")
if phase2_aligned_series.empty:
    print("No alignment-phase bins were produced.")
else:
    display(phase2_aligned_series[["bin_id", "bin_start", "bin_end", "window", "count", "intensity"]].head())

Selected window: 12h
Window unit: hour
Intensity unit: count per hour
Alignment status: no_alignment_needed
Algorithm selected 12h; window unit=hour; intensity unit=count per hour; integer alignment did not change the grid.

Phase 1: raw count-binning output from the original algorithm

   bin_id           bin_start             bin_end window  count  intensity
0       1 2023-04-01 00:00:00 2023-04-01 12:00:00    12h      7      0.583
1       2 2023-04-01 12:00:00 2023-04-02 00:00:00    12h     12      1.000
2       3 2023-04-02 00:00:00 2023-04-02 12:00:00    12h      5      0.417
3       4 2023-04-02 12:00:00 2023-04-03 00:00:00    12h      8      0.667
4       5 2023-04-03 00:00:00 2023-04-03 12:00:00    12h      5      0.417

Phase 2: integer-aligned output from the bin-alignment phase

   bin_id           bin_start             bin_end window  count  intensity
0       1 2023-04-01 00:00:00 2023-04-01 12:00:00    12h      7      0.583
1       2 2023-04-01 12:00:00 2023-04-02 00:00:00    12h     12      1.000
2       3 2023-04-02 00:00:00 2023-04-02 12:00:00    12h      5      0.417
3       4 2023-04-02 12:00:00 2023-04-03 00:00:00    12h      8      0.667
4       5 2023-04-03 00:00:00 2023-04-03 12:00:00    12h      5      0.417